name: Botonic plugin-google-analytics tests

on:
  push:
    paths:
      - 'packages/botonic-plugin-google-analytics/**'
      - '.github/workflows/botonic-plugin-google-analytics-tests.yml'

jobs:
  botonic-plugin-google-analytics-tests:
    name: Botonic plugin-google-analytics tests
    runs-on: ubuntu-latest
    env:
      PACKAGE: botonic-plugin-google-analytics
    steps:
    - name: Checking out to current branch (Step 1 of 6)
      uses: actions/checkout@v1
    - name: Setting up node (Step 2 of 6)
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setting up cache (Step 3 of 6)
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install botonic-plugin-google-analytics (Step 4 of 6)
      run: (cd ./packages/$PACKAGE && npm install -D)
    - name: Install common packages dependencies (Step 5 of 6)
      run: npm install -D
    - name: Verify lint botonic-plugin-google-analytics (Step 6 of 6)
      run: (cd ./packages/$PACKAGE && npm run lint_ci)
